const STRINGS = {
  es: {
    speciality: {
      INT: "Medicina Interna",
      FAM: "Medicina Familiar y Comunitaria",
      PED: "Pediatría",
      GYN: "Ginecología y Obstetricia",
      PSY: "Psiquiatría",
      DER: "Dermatología",
      NEU: "Neurología",
      OPH: "Oftalmología",
      ENT: "Otorrinolaringología",
      ORT: "Traumatología y Ortopedia",
      SUR: "Cirugía General",
      ANE: "Anestesiología",
      ONC: "Oncología Médica",
      RAD: "Radiología / Diagnóstico por Imagen",
      EME: "Medicina de Urgencias / Emergencias",
      OCC: "Medicina del Trabajo",
      PMR: "Medicina Física y Rehabilitación",
      PRE: "Medicina Preventiva y Salud Pública",
      PSI: "Psicología",
      DEN: "Odontologia",
    },
    login: {
      title: "INICIAR SESIÓN",
      emailPlaceHolder: "Correo electrónico",
      passwordPlaceHolder: "Contraseña",
      logIn: "INICIAR SESIÓN",
      forgotPassword: "Olvidaste tu contraseña",
      createAccount: "Crear cuenta",
      country: "País ",
      countryName: "🇪🇨 Ecuador",
      language: "Idioma ",
      selectedLanguage: "Español",
    },
    home: {
      search: "Buscar",
      titleOne: "Tu Salud es",
      titleTwo: "nuestra prioridad",
      surgestion:
        '"Dormir bien, comer bien y \n respirar profundo tambien es \n productividad."',
    },
    signupUser: {
      createAccountTitle1: "Creá una\n",
      createAccountTitle2: "nueva cuenta",
      name: "NOMBRE",
      nationalId: "CÉDULA",
      birthDate: "FECHA DE NACIMIENTO",
      phone: "CELULAR",
      province: "PROVINCIA",
      street: "CALLE",
      email: "CORREO ELECTRÓNICO",
      password: "CONTRASEÑA",
      passwordPlaceholder: "Ej: 1234@Abc",
      confirmPassword: "CONFIRMAR CONTRASEÑA",
      createAccountButton: "Crear cuenta",
      emailInvalid: "Correo electrónico inválido",
      passwordInvalid:
        "La contraseña debe tener al menos 8 caracteres, una mayúscula, una minúscula, un número y un símbolo",
      passwordMismatch: "Las contraseñas no coinciden",
      phoneInvalid: "Número de teléfono inválido",
      nationalIdInvalid: "Cédula inválida",
      birthDateInvalid: "La fecha debe estar en el pasado",

      error1: "Error al registrarse",
      namePlaceholder: "Ejm: Juan Pérez",
      phonePlaceholder: "0999999999",
      nationalIDPlaceholder: "1234567890",
      cancel: "Cancel",
      ok: "Ok",
      done: "Done",
      streetPlaceholder: "Ejm: Machala y Salinas",
      emailPlaceholder: "Ejm: ejemplo@gmail.com",
    },
    doctorSearch: {
      searchLabel: "Nombre, Especialidad",
      seachPlaceholder: "Buscar",
    },
    doctorProfile: {
      bookAppointment: "Agendar Cita",
      selectLocation: "Selecciona un consultorio:",
      phone: "Telefono:",
      email: "Correo:",
      schedule: "Horarios",
      languages: "Idiomas",
      paymentMethod: "Metodos de Pago",
      insurance: "Compañías de seguros",
      profile: "Perfil profesional",
      location: "Ubicación",
      selectLocationAlert: "Por favor seleccione un consultorio",
      morning: "Morning",
      afternoon: "Afternoon",
      fullDay: "Todo el dia",
    },
    appointments: {
      myAppointments: "Mis Citas",
      nextAppointments: "Proximas Citas",
      pastAppointments: "Citas Pasadas",
      name: "Nombre:",
      speciality: "Especialidad: ",
      date: "Fecha: ",
      time: "Hora: ",
      location: "Lugar: ",
      status: "Estado: ",
      dateError:
        "Las citas solo se pueden cancelar por este medio hasta 12h antes de la consulta, pasado este tiempo debera comunicar se con el medico",
      cancelAppointment: "Cancelar Cita",
      bookAgain: "Agendar nuevamente",
      cancelationMessage: "Esta seguro que desea cancelar su cita?",
      confirmButton: "Confirmar",
      closeButton: "Cancelar",
      scheduled: {
        cero: "Agendada",
        uno: "Finalizada",
      },
      cancelled: {
        cero: "Cancelada",
        uno: "Cancelada",
      },
      bookNewAppointment: "Agendar cita",
      openGoogleMaps: "Abrir con Google Maps",
      openWays: "Abrir con Waze",
      openAppleMaps: "Abrir con Apple Maps",
      cancel: "Cancelar",
    },
    account: {
      myProfile: "Mi perfil",
      editProfile: "Editar datos de perfil",
      resetPassword: "Reestablecer contrasena",
      language: "Idioma",
      selectedLanguage: "Espanol",
      logOut: "Cerrar session",
      confirmLogOut: "Esta seguro?",
      languageSelect: "Selecione su idioma",
      closeButton: "Cancelar",
    },
    bookAppointment: {
      noSlots: "No se encuentran horarios disponibles para esta fecha",
      selectDate: "Seleccione una fehca",
      timeSlots: "Horarios disponibles",
      confirmAppointment: "Confirmar Cita",
    },
    daysOfWeek: [
      "Domingo",
      "Lunes",
      "Martes",
      "Miercoles",
      "Jueves",
      "Viernes",
      "Sabado",
    ],
    months: [
      "Enero",
      "Febrero",
      "Marzo",
      "Abril",
      "Mayo",
      "Junio",
      "Julio",
      "Agosto",
      "Septiembre",
      "Octubre",
      "Noviembre",
      "Diciembre",
    ],
    myProfile: {
      emailInvalid: "Correo electrónico inválido",
      oldPasswordInvalid: "Debe ingresar la clave actual",
      passwordInvalid:
        "La contraseña debe tener al menos 8 caracteres, una mayúscula, una minúscula, un número y un símbolo",
      passwordMismatch: "Las contraseñas no coinciden",
      deleteCategory: "Eliminar Categoria",
      eliminar: "Eliminar",
      addCondition: "Agregar condición médica",
      selectCategory: "Seleccione una categoria",
      conditionPlaceholder: "Condición médica",
      addVaccine: "Agregar vacuna",
      vaccineNamePlaceholder: "Nombre de la vacuna",
      date: "Fecha",
      SelectDate: "Seleccione la fecha de la vacuna",
      details: "Datos personales",
      province: "Provincia",
      country: "Pais",
      height: "Altura (cm)",
      weight: "Peso (kg)",
      bloodType: "Tipo de sangre",
      medicalConditions: "Condiciónes médicas",
      vaccines: "Vacunas",
      save: "Guardar cambios",
      oldPassword: "Contraseña actual",
      newPassword: "Nueva contraseña",
      newPasswordConfirm: "Confirma tu nueva contraseña",
      savePassword: "Guardar nueva clave",
      cancel: "Cancelar",
      changePassword: "Cambiar clave",
      closeAccount: "Cerrar cuenta",
      name: "Nombre",
      email: "E-Mail",
      phone: "Telefono",
      address: "Dirección",
      close: "Cerrar",
    },
    medicalCategories: [
      { label: "Enfermedades Infecciosas", value: "IFDI" },
      {
        label: "Enfermedades Cardiovasculares",
        value: "CVDI",
      },
      { label: "Enfermedades Respiratorias", value: "RSDI" },
      { label: "Trastornos Neurológicos", value: "NEDI" },
      { label: "Trastornos de Salud Mental", value: "MHDI" },
      {
        label: "Trastornos Endocrinos y Metabólicos",
        value: "EMDI",
      },
      {
        label: "Trastornos Musculoesqueléticos",
        value: "MSDI",
      },
      {
        label: "Trastornos Gastrointestinales",
        value: "GIDI",
      },
      {
        label: "Trastornos Genéticos y Congénitos",
        value: "GCDI",
      },
      {
        label: "Cánceres (Enfermedades Oncológicas)",
        value: "ONCO",
      },
      {
        label: "Afecciones Dermatológicas",
        value: "DERM",
      },
      {
        label: "Trastornos Renales y Urológicos",
        value: "RUDI",
      },
      {
        label: "Trastornos Hematológicos (de la Sangre)",
        value: "HEMD",
      },
      {
        label: "Trastornos de la Salud Reproductiva",
        value: "RHDI",
      },
      {
        label: "Trastornos del Sistema Inmunológico",
        value: "IMMU",
      },
      {
        label: "Trastornos Oculares (Oftalmología)",
        value: "OPHT",
      },
      {
        label: "Trastornos de Oído, Nariz y Garganta (ORL)",
        value: "ENTI",
      },
      {
        label: "Deficiencias Nutricionales",
        value: "NUDI",
      },
      { label: "Trastornos del Dolor", value: "PAIN" },
      { label: "Condiciones Toxicológicas", value: "TOXI" },
    ],
    medicalCategoryValues: {
      IFDI: "Enfermedades Infecciosas",
      CVDI: "Enfermedades Cardiovasculares",
      RSDI: "Enfermedades Respiratorias",
      NEDI: "Trastornos Neurológicos",
      MHDI: "Trastornos de Salud Mental",
      EMDI: "Trastornos Endocrinos y Metabólicos",
      MSDI: "Trastornos Musculoesqueléticos",
      GIDI: "Trastornos Gastrointestinales",
      GCDI: "Trastornos Genéticos y Congénitos",
      ONCO: "Cánceres (Enfermedades Oncológicas)",
      DERM: "Afecciones Dermatológicas",
      RUDI: "Trastornos Renales y Urológicos",
      HEMD: "Trastornos Hematológicos (de la Sangre)",
      RHDI: "Trastornos de la Salud Reproductiva",
      IMMU: "Trastornos del Sistema Inmunológico",
      OPHT: "Trastornos Oculares (Oftalmología)",
      ENTI: "Trastornos de Oído, Nariz y Garganta (ORL)",
      NUDI: "Deficiencias Nutricionales",
      PAIN: "Trastornos del Dolor",
      TOXI: "Condiciones Toxicológicas",
    },
  },
  en: {
    speciality: {
      INT: "Internal Medicine",
      FAM: "Family and Community Medicine",
      PED: "Pediatrics",
      GYN: "Gynecology and Obstetrics",
      PSY: "Psychiatry",
      DER: "Dermatology",
      NEU: "Neurology",
      OPH: "Ophthalmology",
      ENT: "Otorhinolaryngology",
      ORT: "Traumatology and Orthopedics",
      SUR: "General Surgery",
      ANE: "Anesthesiology",
      ONC: "Medical Oncology",
      RAD: "Radiology / Diagnostic Imaging",
      EME: "Emergency Medicine",
      OCC: "Occupational Medicine",
      PMR: "Physical and Rehabilitation Medicine",
      PRE: "Preventive Medicine and Public Health",
      PSI: "Psychology",
      DEN: "Dentistry",
    },
    login: {
      title: "LOG IN",
      emailPlaceHolder: "Email",
      passwordPlaceHolder: "Password",
      logIn: "LOG IN",
      forgotPassword: "Forgot your password",
      createAccount: "Create account",
      country: "Country",
      countryName: "🇪🇨 Ecuador",
      language: "Language",
      selectedLanguage: "English",
    },
    home: {
      search: "Search",
      titleOne: "Your Health is",
      titleTwo: "our priority",
      surgestion:
        '"Sleeping well, eating well,\n and breathing deeply is\n also productivity."',
    },
    signupUser: {
      createAccountTitle1: "Create a\n",
      createAccountTitle2: "new account",
      name: "NAME",
      nationalId: "NATIONAL ID",
      birthDate: "DATE OF BIRTH",
      phone: "PHONE",
      province: "PROVINCE",
      street: "STREET",
      email: "EMAIL",
      password: "PASSWORD",
      passwordPlaceholder: "Ex: 1234@Abc",
      confirmPassword: "CONFIRM PASSWORD",
      createAccountButton: "Create account",
      emailInvalid: "Invalid email",
      passwordInvalid:
        "Password must be at least 8 characters, with uppercase, lowercase, number, and symbol",
      passwordMismatch: "Passwords do not match",
      phoneInvalid: "Invalid phone number",
      nationalIdInvalid: "Invalid ID",
      birthDateInvalid: "Date must be in the past",
      error1: "Registration error",
      namePlaceholder: "Ex: John Smith",
      phonePlaceholder: "0999999999",
      nationalIDPlaceholder: "1234567890",
      cancel: "Cancel",
      ok: "Ok",
      done: "Done",
      streetPlaceholder: "Ex: Machala and Salinas",
      emailPlaceholder: "Ex: example@gmail.com",
    },
    doctorSearch: {
      searchLabel: "Name, Specialty",
      seachPlaceholder: "Search",
    },
    doctorProfile: {
      bookAppointment: "Book Appointment",
      selectLocation: "Select a clinic:",
      phone: "Phone:",
      email: "Email:",
      schedule: "Schedule",
      languages: "Languages",
      paymentMethod: "Payment Methods",
      insurance: "Insurance Companies",
      profile: "Professional Profile",
      location: "Location",
      selectLocationAlert: "Please select a clinic",
      morning: "Morning",
      afternoon: "Afternoon",
      fullDay: "Full Day",
    },
    appointments: {
      myAppointments: "My Appointments",
      nextAppointments: "Upcoming Appointments",
      pastAppointments: "Past Appointments",
      name: "Name:",
      speciality: "Specialty:",
      date: "Date:",
      time: "Time:",
      location: "Place:",
      status: "Status:",
      dateError:
        "Appointments can only be canceled through this method up to 12h before. After that, contact the doctor directly.",
      cancelAppointment: "Cancel Appointment",
      bookAgain: "Book Again",
      cancelationMessage: "Are you sure you want to cancel this appointment?",
      confirmButton: "Confirm",
      closeButton: "Cancel",
      scheduled: {
        cero: "Scheduled",
        uno: "Completed",
      },
      cancelled: {
        cero: "Canceled",
        uno: "Canceled",
      },
      bookNewAppointment: "Book appointment",
      openGoogleMaps: "Open with Google Maps",
      openWays: "Open with Waze",
      openAppleMaps: "Open with Apple Maps",
      cancel: "Cancel",
    },
    account: {
      myProfile: "My Profile",
      editProfile: "Edit Profile",
      resetPassword: "Reset Password",
      language: "Language",
      selectedLanguage: "English",
      logOut: "Log Out",
      confirmLogOut: "Are you sure?",
      languageSelect: "Select your language",
      closeButton: "Cancel",
    },
    bookAppointment: {
      noSlots: "No available slots for this date",
      selectDate: "Select a date",
      timeSlots: "Available times",
      confirmAppointment: "Confirm Appointment",
    },
    daysOfWeek: [
      "Sunday",
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
    ],
    months: [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December",
    ],
    myProfile: {
      emailInvalid: "Invalid email",
      oldPasswordInvalid: "Current password required",
      passwordInvalid:
        "Password must be at least 8 characters, with uppercase, lowercase, number, and symbol",
      passwordMismatch: "Passwords do not match",
      deleteCategory: "Delete Category",
      eliminar: "Delete",
      addCondition: "Add medical condition",
      selectCategory: "Select a category",
      conditionPlaceholder: "Medical condition",
      addVaccine: "Add vaccine",
      vaccineNamePlaceholder: "Vaccine name",
      date: "Date",
      SelectDate: "Select the vaccine date",
      details: "Personal details",
      province: "Province",
      country: "Country",
      height: "Height (cm)",
      weight: "Weight (kg)",
      bloodType: "Blood type",
      medicalConditions: "Medical conditions",
      vaccines: "Vaccines",
      save: "Save changes",
      oldPassword: "Current password",
      newPassword: "New password",
      newPasswordConfirm: "Confirm new password",
      savePassword: "Save new password",
      cancel: "Cancel",
      changePassword: "Change password",
      closeAccount: "Close account",
      name: "Name",
      email: "E-Mail",
      phone: "Phone",
      address: "Adrress",
      close: "Close",
    },
    medicalCategories: [
      { label: "Infectious Diseases", value: "IFDI" },
      { label: "Cardiovascular Diseases", value: "CVDI" },
      { label: "Respiratory Diseases", value: "RSDI" },
      { label: "Neurological Disorders", value: "NEDI" },
      { label: "Mental Health Disorders", value: "MHDI" },
      { label: "Endocrine and Metabolic Disorders", value: "EMDI" },
      { label: "Musculoskeletal Disorders", value: "MSDI" },
      { label: "Gastrointestinal Disorders", value: "GIDI" },
      { label: "Genetic and Congenital Disorders", value: "GCDI" },
      { label: "Cancers (Oncological Diseases)", value: "ONCO" },
      { label: "Dermatological Conditions", value: "DERM" },
      { label: "Renal and Urological Disorders", value: "RUDI" },
      { label: "Hematologic Disorders (Blood)", value: "HEMD" },
      { label: "Reproductive Health Disorders", value: "RHDI" },
      { label: "Immune System Disorders", value: "IMMU" },
      { label: "Ocular Disorders (Ophthalmology)", value: "OPHT" },
      { label: "Ear, Nose, and Throat Disorders (ENT)", value: "ENTI" },
      { label: "Nutritional Deficiencies", value: "NUDI" },
      { label: "Pain Disorders", value: "PAIN" },
      { label: "Toxicological Conditions", value: "TOXI" },
    ],
    medicalCategoryValues: {
      IFDI: "Infectious Diseases",
      CVDI: "Cardiovascular Diseases",
      RSDI: "Respiratory Diseases",
      NEDI: "Neurological Disorders",
      MHDI: "Mental Health Disorders",
      EMDI: "Endocrine and Metabolic Disorders",
      MSDI: "Musculoskeletal Disorders",
      GIDI: "Gastrointestinal Disorders",
      GCDI: "Genetic and Congenital Disorders",
      ONCO: "Cancers (Oncological Diseases)",
      DERM: "Dermatological Conditions",
      RUDI: "Renal and Urological Disorders",
      HEMD: "Hematologic Disorders (Blood)",
      RHDI: "Reproductive Health Disorders",
      IMMU: "Immune System Disorders",
      OPHT: "Ocular Disorders (Ophthalmology)",
      ENTI: "Ear, Nose, and Throat Disorders (ENT)",
      NUDI: "Nutritional Deficiencies",
      PAIN: "Pain Disorders",
      TOXI: "Toxicological Conditions",
    },
  },
};

export default STRINGS;
