const STRINGS = {
  es: {
    speciality: {
      INT: "Medicina Interna",
      FAM: "Medicina Familiar y Comunitaria",
      PED: "Pediatría",
      GYN: "Ginecología y Obstetricia",
      PSY: "Psiquiatría",
      DER: "Dermatología",
      NEU: "Neurología",
      OPH: "Oftalmología",
      ENT: "Otorrinolaringología",
      ORT: "Traumatología y Ortopedia",
      SUR: "Cirugía General",
      ANE: "Anestesiología",
      ONC: "Oncología Médica",
      RAD: "Radiología / Diagnóstico por Imagen",
      EME: "Medicina de Urgencias / Emergencias",
      OCC: "Medicina del Trabajo",
      PMR: "Medicina Física y Rehabilitación",
      PRE: "Medicina Preventiva y Salud Pública",
      PSI: "Psicología",
      DEN: "Odontologia",
    },
    login: {
      title: "INICIA SESIÓN",
      emailPlaceHolder: "Correo electrónico",
      passwordPlaceHolder: "Contraseña",
      logIn: "INICIA SESIÓN",
      forgotPassword: "Olvidaste tu contraseña",
      createAccount: "Crear cuenta",
      country: "País ",
      countryName: "🇪🇨 Ecuador",
      language: "Idioma ",
      selectedLanguage: "Español",
    },
    home: {
      search: "Buscar",
      titleOne: "Tu Salud es",
      titleTwo: "nuestra prioridad",
      surgestion:
        '"Dormir bien, comer bien y \n respirar profundo tambien es \n productividad."',
    },
    signupUser: {
      createAccountTitle1: "Creá una\n",
      createAccountTitle2: "nueva cuenta",

      name: "NOMBRE",
      nationalId: "CÉDULA",
      birthDate: "FECHA DE NACIMIENTO",
      phone: "CELULAR",
      province: "PROVINCIA",
      street: "CALLE",
      email: "CORREO ELECTRÓNICO",
      password: "CONTRASEÑA",
      passwordPlaceholder: "Ej: 1234@Abc",
      confirmPassword: "CONFIRMAR CONTRASEÑA",
      createAccountButton: "Crear cuenta",
      emailInvalid: "Correo electrónico inválido",
      passwordInvalid:
        "La contraseña debe tener al menos 8 caracteres, una mayúscula, una minúscula, un número y un símbolo",
      passwordMismatch: "Las contraseñas no coinciden",
      phoneInvalid: "Número de teléfono inválido",
      nationalIdInvalid: "Cédula inválida",
      birthDateInvalid: "La fecha debe estar en el pasado",

      error1: "Error al registrarse",
      namePlaceholder: "Ejm: Juan Pérez",
      phonePlaceholder: "0999999999",
      nationalIDPlaceholder: "1234567890",
      cancel: "Cancel",
      ok: "Ok",
      done: "Done",
      streetPlaceholder: "Ejm: Machala y Salinas",
      emailPlaceholder: "Ejm: ejemplo@gmail.com",
    },
    doctorSearch: {
      searchLabel: "Nombre, Especialidad",
      seachPlaceholder: "Buscar",
    },
    doctorProfile: {
      bookAppointment: "Agendar Cita",
      selectLocation: "Selecciona un consultorio:",
      phone: "Telefono:",
      email: "Correo:",
      schedule: "Horarios",
      languages: "Idiomas",
      paymentMethod: "Metodos de Pago",
      insurance: "Compañías de seguros",
      profile: "Perfil profesional",
      location: "Ubicación",
      // new
      selectLocationAlert: "Porfavor seleccione un consultorio",
      morning: "Morning",
      afternoon: "Afternoon",
      fullDay: "Todo el dia",
    },
    appointments: {
      myAppointments: "Mis Citas",
      nextAppointments: "Proximas Citas",
      pastAppointments: "Citas Pasadas",
      name: "Nombre:",
      speciality: "Especialidad: ",
      date: "Fecha: ",
      time: "Hora: ",
      location: "Lugar: ",
      status: "Estado: ",
      dateError:
        "Las citas solo se pueden cancelar por este medio hasta 12h antes de la consulta, pasado este tiempo debera comunicar se con el medico",
      cancelAppointment: "Cancelar Cita",
      bookAgain: "Agendar nuevamente",
      cancelationMessage: "Esta seguro que desea cancelar su cita?",
      confirmButton: "Confirmar",
      closeButton: "Cerrar",
      scheduled: {
        cero: "Agendada",
        uno: "Finalizada",
      },
      cancelled: {
        cero: "Cancelada",
        uno: "Cancelada",
      },
      bookNewAppointment: "Agendar cita",
    },
    account: {
      myProfile: "Mi perfil",
      editProfile: "Editar datos de perfil",
      resetPassword: "Reestablecer contrasena",
      language: "Idioma",
      selectedLanguage: "Espanol",
      logOut: "Cerrar session",
      confirmLogOut: "Esta seguro?",
      languageSelect: "Selecione su idioma",
      closeButton: "Cerrar",
    },
    bookAppointment: {
      noSlots: "No se encuentran horarios disponibles para esta fecha",
      selectDate: "Seleccione una fehca",
      timeSlots: "Horarios disponibles",
      confirmAppointment: "Confirmar Cita",
    },
    daysOfWeek: [
      "Domingo",
      "Lunes",
      "Martes",
      "Miercoles",
      "Jueves",
      "Viernes",
      "Sabado",
    ],
    months: [
      "Enero",
      "Febrero",
      "Marzo",
      "Abril",
      "Mayo",
      "Junio",
      "Julio",
      "Agosto",
      "Septiembre",
      "Octubre",
      "Noviembre",
      "Diciembre",
    ],
  },
  en: {
    login: {
      title: "LOG IN",
      emailPlaceHolder: "Email",
      passwordPlaceHolder: "Password",
      logIn: "LOG IN",
      forgotPassword: "Forgot your password",
      createAccount: "Create account",
      country: "Country ",
      countryName: "🇪🇨 Ecuador",
      language: "Language ",
      selectedLanguage: "English",
    },
    home: {
      search: "Search",
      titleOne: "Your health is",
      titleTwo: "our priority",
      surgestion:
        '"Sleeping well, eating well, and \n breathing deeply is also \n productivity."',
    },
    signupUser: {
      createAccountTitle1: "Create a\n",
      createAccountTitle2: "new account",

      name: "NAME",
      nationalId: "NATIONAL ID",
      birthDate: "DATE OF BIRTH",
      phone: "PHONE",
      province: "PROVINCE",
      street: "STREET",
      email: "EMAIL",
      password: "PASSWORD",
      passwordPlaceholder: "Ex: 1234@Abc",
      confirmPassword: "CONFIRM PASSWORD",
      createAccountButton: "Create account",
      emailInvalid: "Invalid email address",
      passwordInvalid:
        "Password must be at least 8 characters long and contain an uppercase letter, a lowercase letter, a number, and a symbol",
      passwordMismatch: "Passwords do not match",
      phoneInvalid: "Invalid phone number",
      nationalIdInvalid: "Invalid national ID",
      birthDateInvalid: "The date must be in the past",
      error1: "Error during registration",
      namePlaceholder: "Ex: John Smith",
      phonePlaceholder: "0999999999",
      nationalIDPlaceholder: "1234567890",
      cancel: "Cancel",
      ok: "Ok",
      done: "Done",
      streetPlaceholder: "Ex: Machala y Salinas",
      emailPlaceholder: "Ex: example@gmail.com",
    },
    doctorSearch: {
      searchLabel: "Name, Specialty",
      searchPlaceholder: "Search",
    },
    doctorProfile: {
      bookAppointment: "Book Appointment",
      selectLocation: "Select a location:",
      phone: "Phone:",
      email: "Email:",
      schedule: "Schedule",
      languages: "Languages",
      paymentMethod: "Payment Methods",
      insurance: "Insurance Companies",
      profile: "Professional Profile",
      location: "Location",
    },
    appointments: {
      myAppointments: "My Appointments",
      nextAppointments: "Upcoming Appointments",
      pastAppointments: "Past Appointments",
      name: "Name: ",
      speciality: "Specialty: ",
      time: "Time: ",
      date: "Date: ",
      location: "Location: ",
      status: "Status: ",
      dateError:
        "Appointments can only be canceled through this app up to 12 hours before the appointment. After that, you must contact the doctor directly.",
      cancelAppointment: "Cancel Appointment",
      bookAgain: "Book Again",
      cancelationMessage: "Are you sure you want to cancel your appointment?",
      confirmButton: "Confirm",
      closeButton: "Close",
      scheduled: {
        cero: "Scheduled",
        uno: "Completed",
      },
      cancelled: {
        cero: "Cancelled",
        uno: "Cancelled",
      },
      bookNewAppointment: "Book appointment",
    },
    account: {
      myProfile: "My Profile",
      editProfile: "Edit Profile Information",
      resetPassword: "Reset Password",
      language: "Language",
      selectedLanguage: "English",
      logOut: "Log Out",
      confirmLogOut: "Are you sure?",
      languageSelect: "Select your language",
      closeButton: "Close",
    },
    bookAppointment: {
      noSlots: "No available time slots for this date",
      selectDate: "Select a date",
      timeSlots: "Available time slots",
      confirmAppointment: "Confirm Appointment",
    },
    speciality: {
      INT: "Internal Medicine",
      FAM: "Family and Community Medicine",
      PED: "Pediatrics",
      GYN: "Gynecology and Obstetrics",
      PSY: "Psychiatry",
      DER: "Dermatology",
      NEU: "Neurology",
      OPH: "Ophthalmology",
      ENT: "Otorhinolaryngology",
      ORT: "Traumatology and Orthopedics",
      SUR: "General Surgery",
      ANE: "Anesthesiology",
      ONC: "Medical Oncology",
      RAD: "Radiology / Diagnostic Imaging",
      EME: "Emergency Medicine",
      OCC: "Occupational Medicine",
      PMR: "Physical Medicine and Rehabilitation",
      PRE: "Preventive Medicine and Public Health",
      PSI: "Psychology",
      DEN: "Dentistry",
    },
    daysOfWeek: [
      "Sunday",
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
    ],
    months: [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December",
    ],
  },
};

export default STRINGS;
