const STRINGS = {
  es: {
    login: {
      title: "INICIA SESIÓN",
      emailPlaceHolder: "Correo electrónico",
      passwordPlaceHolder: "Contraseña",
      logIn: "INICIA SESIÓN",
      forgotPassword: "Olvidaste tu contraseña",
      createAccount: "Crear cuenta",
      country: "País ",
      countryName: "Ecuador",
      language: "Idioma ",
      selectedLanguage: "Español",
    },
    home: {
      search: "Buscar",
      titleOne: "Tu Salud es",
      titleTwo: "nuestra prioridad",
      surgestion:
        '"Dormir bien, comer bien y \n respirar profundo tambien es \n productividad."',
    },
    singupUser: {
      createAccountTitle1: "Creá una\n",
      createAccountTitle2: "nueva cuenta",

      name: "NOMBRE",
      nationalId: "CÉDULA",
      birthDate: "FECHA DE NACIMIENTO",
      phone: "CELULAR",
      province: "PROVINCIA",
      street: "CALLE",
      email: "CORREO ELECTRÓNICO",
      password: "CONTRASEÑA",
      passwordPlaceholder: "Ej: 1234@Abc",
      confirmPassword: "CONFIRMAR CONTRASEÑA",
      createAccountButton: "Crear cuenta",
      emailInvalid: "Correo electrónico inválido",
      passwordInvalid:
        "La contraseña debe tener al menos 8 caracteres, una mayúscula, una minúscula, un número y un símbolo",
      passwordMismatch: "Las contraseñas no coinciden",
      phoneInvalid: "Número de teléfono inválido",
      nationalIdInvalid: "Cédula inválida",
      birthDateInvalid: "La fecha debe estar en el pasado",

      error1: "Error al registrarse",
      namePlaceholder: "Ejm: Juan Pérez",
      phonePlaceholder: "0999999999",
      nationalIDPlaceholder: "1234567890",
      cancel: "Cancel",
      ok: "Ok",
      done: "Done",
      streetPlaceholder: "Ejm: Machala y Salinas",
      emailPlaceholder: "Ejm: ejemplo@gmail.com",
      provinces: [
        { label: "Azuay", value: "azuay" },
        { label: "Bolívar", value: "bolivar" },
        { label: "Cañar", value: "canar" },
        { label: "Carchi", value: "carchi" },
        { label: "Chimborazo", value: "chimborazo" },
        { label: "Cotopaxi", value: "cotopaxi" },
        { label: "El Oro", value: "el_oro" },
        { label: "Esmeraldas", value: "esmeraldas" },
        { label: "Galápagos", value: "galapagos" },
        { label: "Guayas", value: "guayas" },
        { label: "Imbabura", value: "imbabura" },
        { label: "Loja", value: "loja" },
        { label: "Los Ríos", value: "los_rios" },
        { label: "Manabí", value: "manabi" },
        { label: "Morona Santiago", value: "morona_santiago" },
        { label: "Napo", value: "napo" },
        { label: "Orellana", value: "orellana" },
        { label: "Pastaza", value: "pastaza" },
        { label: "Pichincha", value: "pichincha" },
        { label: "Santa Elena", value: "santa_elena" },
        { label: "Santo Domingo de los Tsáchilas", value: "santo_domingo" },
        { label: "Sucumbíos", value: "sucumbios" },
        { label: "Tungurahua", value: "tungurahua" },
        { label: "Zamora Chinchipe", value: "zamora_chinchipe" },
      ],
    },
    doctorSearch: {
      searchLabel: "Nombre, Especialidad",
      seachPlaceholder: "Buscar",
    },
    doctorProfile: {
      bookAppointment: "Agendar Cita",
      selectLocation: "Selecciona un consultorio:",
      phone: "Telefono:",
      email: "Correo:",
      schedule: "Horarios",
      languages: "Idiomas",
      paymentMethod: "Metodos de Pago",
      insurance: "Compañías de seguros",
    },
    appointments: {
      myAppointments: "Mis Citas",
      nextAppointments: "Proximas Citas",
      pastAppointments: "Citas Pasadas"
    },
  },
  en: {
    login: {
      title: "LOG IN",
      emailPlaceHolder: "Email",
      passwordPlaceHolder: "Password",
      logIn: "LOG IN",
      forgotPassword: "Forgot your password",
      createAccount: "Create account",
      country: "Country ",
      countryName: "Ecuador",
      language: "Language ",
      selectedLanguage: "English",
    },
    home: {
      search: "Search",
      titleOne: "Your health is",
      titleTwo: "our priority",
      surgestion:
        '"Sleeping well, eating well, and \n breathing deeply is also \n productivity."',
    },
    singupUser: {
      createAccountTitle1: "Create a\n",
      createAccountTitle2: "new account",
  
      name: "NAME",
      nationalId: "NATIONAL ID",
      birthDate: "DATE OF BIRTH",
      phone: "PHONE",
      province: "PROVINCE",
      street: "STREET",
      email: "EMAIL",
      password: "PASSWORD",
      passwordPlaceholder: "Ex: 1234@Abc",
      confirmPassword: "CONFIRM PASSWORD",
      createAccountButton: "Create account",
      emailInvalid: "Invalid email address",
      passwordInvalid:
        "Password must be at least 8 characters long and contain an uppercase letter, a lowercase letter, a number, and a symbol",
      passwordMismatch: "Passwords do not match",
      phoneInvalid: "Invalid phone number",
      nationalIdInvalid: "Invalid national ID",
      birthDateInvalid: "The date must be in the past",
  
      error1: "Error during registration",
      namePlaceholder: "Ex: John Smith",
      phonePlaceholder: "0999999999",
      nationalIDPlaceholder: "1234567890",
      cancel: "Cancel",
      ok: "Ok",
      done: "Done",
      streetPlaceholder: "Ex: Machala y Salinas",
      emailPlaceholder: "Ex: example@gmail.com",
      provinces: [
        { label: "Azuay", value: "azuay" },
        { label: "Bolívar", value: "bolivar" },
        { label: "Cañar", value: "canar" },
        { label: "Carchi", value: "carchi" },
        { label: "Chimborazo", value: "chimborazo" },
        { label: "Cotopaxi", value: "cotopaxi" },
        { label: "El Oro", value: "el_oro" },
        { label: "Esmeraldas", value: "esmeraldas" },
        { label: "Galápagos", value: "galapagos" },
        { label: "Guayas", value: "guayas" },
        { label: "Imbabura", value: "imbabura" },
        { label: "Loja", value: "loja" },
        { label: "Los Ríos", value: "los_rios" },
        { label: "Manabí", value: "manabi" },
        { label: "Morona Santiago", value: "morona_santiago" },
        { label: "Napo", value: "napo" },
        { label: "Orellana", value: "orellana" },
        { label: "Pastaza", value: "pastaza" },
        { label: "Pichincha", value: "pichincha" },
        { label: "Santa Elena", value: "santa_elena" },
        { label: "Santo Domingo de los Tsáchilas", value: "santo_domingo" },
        { label: "Sucumbíos", value: "sucumbios" },
        { label: "Tungurahua", value: "tungurahua" },
        { label: "Zamora Chinchipe", value: "zamora_chinchipe" },
      ],
    },
    doctorSearch: {
      searchLabel: "Name, Specialty",
      searchPlaceholder: "Search",
    },
    doctorProfile: {
      bookAppointment: "Book Appointment",
      selectLocation: "Select a location:",
      phone: "Phone:",
      email: "Email:",
      schedule: "Schedule",
      languages: "Languages",
      paymentMethod: "Payment Methods",
      insurance: "Insurance Companies",
    },
    appointments: {
      myAppointments: "My Appointments",
      nextAppointments: "Upcoming Appointments",
      pastAppointments: "Past Appointments",
    },
  },
};

export default STRINGS;
