export const provinces = [
  { label: "Azuay", value: "azuay" },
  { label: "Bolívar", value: "bolivar" },
  { label: "Cañar", value: "canar" },
  { label: "Carchi", value: "carchi" },
  { label: "Chimborazo", value: "chimborazo" },
  { label: "Cotopaxi", value: "cotopaxi" },
  { label: "El Oro", value: "el_oro" },
  { label: "Esmeraldas", value: "esmeraldas" },
  { label: "Galápagos", value: "galapagos" },
  { label: "Guayas", value: "guayas" },
  { label: "Imbabura", value: "imbabura" },
  { label: "Loja", value: "loja" },
  { label: "Los Ríos", value: "los_rios" },
  { label: "Manabí", value: "manabi" },
  { label: "Morona Santiago", value: "morona_santiago" },
  { label: "Napo", value: "napo" },
  { label: "Orellana", value: "orellana" },
  { label: "Pastaza", value: "pastaza" },
  { label: "Pichincha", value: "pichincha" },
  { label: "Santa Elena", value: "santa_elena" },
  { label: "Santo Domingo de los Tsáchilas", value: "santo_domingo" },
  { label: "Sucumbíos", value: "sucumbios" },
  { label: "Tungurahua", value: "tungurahua" },
  { label: "Zamora Chinchipe", value: "zamora_chinchipe" },
];
export const languages = [
  { code: "en", label: "English" },
  { code: "es", label: "Español" },
];
